### ISSUE TITLE
DATA FOR TOTAL IS LOWER THAN THIS YEAR

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/tempo#401]
related issues: 150, 139, 134, 42

1. Spend partner, see insights (Android, Samsung Internet)(150)
Data for since I joined Tempo is lower than this year. Data for since I joined Tempo does not update as TC are spent with me
![thumbnail (1)](https://user-images.githubusercontent.com/23721486/82035249-901ce280-969f-11ea-99cb-1f5ad1fcae2e.jpeg)
![thumbnail](https://user-images.githubusercontent.com/23721486/82035258-91e6a600-969f-11ea-85fa-bb928f435d5b.jpeg)

2. Earn group, dashboard (Android, Samsung Internet)(139)
Home page - All time data is lower than this month/year data - query issue?
![thumbnail (2)](https://user-images.githubusercontent.com/23721486/82035329-a9be2a00-969f-11ea-9090-b4940c01f22d.jpeg)
![thumbnail (3)](https://user-images.githubusercontent.com/23721486/82035337-ac208400-969f-11ea-8089-0dab3622f890.jpeg)

3. Earn group, see statistics on how many Time Credits earned, spent and gifted by members  (Google Chrome 81 on Windows 10)(134)
All Time figures are lower than This Month
![thumbnail (1)](https://user-images.githubusercontent.com/23721486/82035468-d5d9ab00-969f-11ea-81c8-1ab5ec70b459.jpeg)
![thumbnail](https://user-images.githubusercontent.com/23721486/82035481-d8d49b80-969f-11ea-94d9-7adf572ca730.jpeg)

4 Earn group, see statistics on how many Time Credits earned, spent and gifted by members  (Google Chrome 81 on Windows 10)(42)
https://tempo365.sharepoint.com/Digital/MVP%202020/Forms/AllItems.aspx?originalPath=aHR0cHM6Ly90ZW1wbzM2NS5zaGFyZXBvaW50LmNvbS86ZjovZy9EaWdpdGFsL0VpRldzMzlYTFRCSHVzQU5iRVRnY3pFQjNxaVBhRndET0pjQlRXVGJqUnEzVlE%5FcnRpbWU9X0R5V21hVDQxMGc&id=%2FDigital%2FMVP%202020%2FTesting%2FR1%20Testing%2FBug%20Reporting%2FBug%2042%2Emp4&parent=%2FDigital%2FMVP%202020%2FTesting%2FR1%20Testing%2FBug%20Reporting

All-time figure is lower than those per year or month

**Comment by RamyAlshurafa** [comment]
@thejoefriel 
fixed

**Comment by thejoefriel** [comment]
@RamyAlshurafa  @ashatat  The stats in earn group is still not fixed. Video again here: 
https://www.loom.com/share/0b7b99ae55fc4874a9d06c4ef4672c40

All time should not be less that the other stats in any of the fields. It's the total amount and therefore should always be the highest number. 

If there's any confusion on this please let me know :) As it has been said this has been fixed quite a few times and then it isn't

**Comment by ashatat** [comment]
@thejoefriel 
Can you count and let me know which is incorrect?
Is this been tested on production build? 
`npm run build:production-db`

**Comment by thejoefriel** [comment]
Yes @ashatat I tested this on the production database build 

You can see in the video that Tempo Time Credits Given Out is incorrect. For some reason it shows it as 7 when it should be 8. I also just went back to test it again now and it now says 5 (rather than 8).

**Comment by ashatat** [comment]
Can you do a backup for your db?

I believe you should run
`pg_dump dbname > filename`
And send the file over 

Let me know if the command didn't work

**Comment by thejoefriel** [comment]
I think this worked @ashatat :
[dbstore_joe.zip](https://github.com/yalla-coop/tempo/files/4644212/dbstore_joe.zip)

Let me know if any issues
